name: CI
on: [push, pull_request]

env:
  BUILD_PROFILE: Release

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
      - name: Build
        run: msbuild /p:Configuration=${{ env.BUILD_PROFILE }}
      - name: See folder struct
        run: tree /F
      - name: See folder struct (root1)
        run: |
          cd ..
          tree /F
      - name: See folder struct (root2)
        run: |
          cd ..
          cd ..
          tree /F
      - name: See folder struct (root3)
        run: |
          cd ..
          cd ..
          cd ..
          tree /F
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            x64/${{ env.BUILD_PROFILE }}/*.*
